### ISSUE TITLE
Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

### ISSUE THREAD

**Issue by Pranathi-Cumulations** [rive-app/rive-android#323] opened 2024-04-01 10:44 UTC
I am facing the above issue with google devices mainly Pixel 6 pro , not able to reproduce it but got noticed in the firebase crashlytics

Using version 8.7.0

Device
Brand:Google
Model:Pixel 6 Pro
Orientation:Portrait
RAM free: 1.91 GB
Disk free: 1.56 GB

 Using the Manifiest method to initialize

**Comment by umberto-sonnino** [comment] 2024-04-03 15:28
Hi @Pranathi-Cumulations this has been reported [here](https://github.com/rive-app/rive-android/issues/305) and it is currently believed to be related only to Play Store devices and not to real users. 
Going to close this issue for now, if you have a more detailed report and a repro we'd be happy to take a look at this!

**Closed by umberto-sonnino** 2024-04-03 15:28 UTC

**Comment by Pranathi-Cumulations** [comment] 2024-04-03 16:45
Hi, thanks for the reply, but I am pretty sure that some of them are not
play Store devices.Because I have not uploaded any build to play store in
that period wheb the crash happened

**Comment by harisAsterbyte** [comment] 2024-04-17 07:19
@umberto-sonnino same issue happening for me in real devices. more than 30 users. spiking this issue now. please give me the solution.

**Log details:** 
Fatal Exception: java.lang.RuntimeException
Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "librive-android.so"...

Devices

-  Samsung(Galaxy Note3, Galaxy Tab4 10.1, Galaxy Tab4 10.0)
- Oppo Reno 9 Pro+ 5G
- Xperia Z2 Tablet
- YogaTablet2 -1050F

**Comment by Lukmannudin** [comment] 2024-06-09 20:40
Hi @umberto-sonnino,

It seems this issue still persists. Although I can't reproduce it on my end, we've received several reports from version 9.3.6 indicating the following error:

"Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: []."

**Comment by ErikUggeldahl** [comment] 2025-06-10 22:21
@jamesonwilliams We recently released an improvement to ReLinker where we now include the `recursively()` flag. This was in [10.1.6](https://github.com/rive-app/rive-android/releases/tag/10.1.6). Could you give that a try and see if it improves things for you?

**Comment by jamesonwilliams** [comment] 2025-06-10 22:24
@ErikUggeldahl Ah, very cool! Yes, we'll give this a try and report back.

**Comment by 15189611** [comment] 2025-09-15 02:29
@ErikUggeldahl @umberto-sonnino  it seems this issue Caused by androidx.startup.StartupException
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

**Comment by sgrosz** [comment] 2025-10-01 14:54
We are also getting this crash and we are running 10.4.1 version of the Rive library. At the moment the crash reports we are getting are only for Pixel 6 Pro running Android 12.

```
Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.MissingLibraryException.<init>(MissingLibraryException.java:22)
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:55)
       at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:45)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:42)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:40)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:138)
       at androidx.startup.AppInitializer.initializeComponent(AppInitializer.java:117)
       at ...onCreate(...)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
       at android.app.ActivityThread.access$1500(ActivityThread.java:256)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

**Comment by sahilpocketfm** [comment] 2025-11-06 06:16
I'm facing the same issue on 10.4.4 version. Any solution for this?

**Comment by vegeta2102** [comment] 2026-01-20 02:32
I'm still facing this issue on Pixel 6 Pro (Android 12)
```
Fatal Exception: java.lang.RuntimeException
Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
```

**Comment by gareys** [comment] 2026-01-29 22:16
+1 Seeing this as well for android 12 users

```
Fatal Exception: java.lang.RuntimeException
Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
```

Please reopen the issue

**Comment by Velord** [comment] 2026-02-06 13:31
`Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libandroid.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].`

This issue has 26 crash events affecting 7 users for last 7 days.
88% Android 9
12% Android 8
Device states are 23% background
35% Samsung
27% Huawei
23% Xiaomi
15% ZTE

Lib version is "11.1.0"

One of the stacktrace:
   ```
       Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libandroid.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.MissingLibraryException.<init>(MissingLibraryException.java:22)
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:197)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:57)
       at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:46)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:38)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:36)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:239)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:207)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1952)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
       at android.app.ActivityThread.installProvider(ActivityThread.java:6638)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6147)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
       at android.app.ActivityThread.access$2000(ActivityThread.java:225)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1802)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:7049)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:913)
```
        
If you need more info feel free to ask.
